Optimized terminal output on deb package scripts

diff --git a/debmatic/DEBIAN/postinst b/debmatic/DEBIAN/postinst
--- a/debmatic/DEBIAN/postinst
+++ b/debmatic/DEBIAN/postinst
@@ -3,49 +3,80 @@ CONFIGFILE=/etc/default/debmatic
 
 . /usr/share/debconf/confmodule
 
-set -e
+function throw {
+  echo $1
+  exit 1
+}
+
+function run {
+  echo -n "$1 ... "
+  shift
+  ERR=`$* 2>&1` && RC=$? || RC=$?
+  if [ $RC -eq 0 ]; then
+    echo -e "\033[0;32mDone\033[0;0m"
+  else
+    echo -e "\033[1;91mFAILED\033[0;0m"
+    echo "$ERR"
+    exit 1
+  fi
+}
+
+function fix_tcl_symlink {
+  if [ -d /lib/tcl8.2 ] && [ ! -L /lib/tcl8.2 ] && [ `find /lib/tcl8.2/ | tail -n +2 | wc -l` -eq 0 ]; then
+    rmdir /lib/tcl8.2 || throw "Could not remove /lib/tcl8.2"
+    ln -s /usr/share/debmatic/lib/tcl8.2 /lib/tcl8.2 || throw "Could not create symlink /lib/tcl8.2"
+  fi
+}
+
+function reload_udev {
+  udevadm control --reload-rules && udevadm trigger || throw "Could not reload udev rules"
+}
+
+function create_debmatic_symlinks {
+  if [ ! -e /usr/sbin/debmatic-info ]; then
+    ln -s /usr/share/debmatic/bin/debmatic-info.sh /usr/sbin/debmatic-info || throw "Could not create debmatic-info symlink"
+  fi
+  if [ ! -e /usr/sbin/debmatic-backup ]; then
+    ln -s /usr/share/debmatic/bin/debmatic-backup.sh /usr/sbin/debmatic-backup || throw "Could not create debmatic-backup symlink"
+  fi
+}
+
+function enable_debmatic_services {
+  for service in `ls /lib/systemd/system/debmatic*.service | xargs -n 1 basename`
+  do
+    if [ ! -e /lib/systemd/system/"${service%.service}.timer" ]; then
+      systemctl enable $service || throw "Could not enable service $service"
+    fi
+  done
+  for timer in `ls /lib/systemd/system/debmatic*.timer | xargs -n 1 basename`
+  do
+    systemctl enable $timer || throw "Could not enable timer $timer"
+  done
+}
+
+function enable_lighttpd_mod {
+  lighttpd-enable-mod debmatic || throw "Could not enable debmatic lighttpd module"
+  systemctl force-reload lighttpd.service || throw "Could not reload lighttpd configuration"
+}
+
+function run_postinst_hooks {
+  if [ -d /usr/share/debmatic/hooks/postinst ]; then
+    run-parts /usr/share/debmatic/hooks/postinst || throw "Failed to run postinst hooks"
+  fi
+}
 
 case "$1" in
   configure|abort-upgrade)
-    ldconfig
-
-    if [ -d /lib/tcl8.2 ] && [ ! -L /lib/tcl8.2 ] && [ `find /lib/tcl8.2/ | tail -n +2 | wc -l` -eq 0 ]; then
-      rmdir /lib/tcl8.2
-      ln -s /usr/share/debmatic/lib/tcl8.2 /lib/tcl8.2
-    fi
-
-    udevadm control --reload-rules && udevadm trigger
-
-    if [ ! -e /usr/sbin/debmatic-info ]; then
-      ln -s /usr/share/debmatic/bin/debmatic-info.sh /usr/sbin/debmatic-info
-    fi
-    if [ ! -e /usr/sbin/debmatic-backup ]; then
-      ln -s /usr/share/debmatic/bin/debmatic-backup.sh /usr/sbin/debmatic-backup
-    fi
-
-    cp /usr/share/debmatic/VERSION /boot/VERSION
-
-    systemctl daemon-reload
-
-    for service in `ls /lib/systemd/system/debmatic*.service | xargs -n 1 basename`
-    do
-      if [ ! -e /lib/systemd/system/"${service%.service}.timer" ]; then
-        systemctl enable $service
-      fi
-    done
-    for timer in `ls /lib/systemd/system/debmatic*.timer | xargs -n 1 basename`
-    do
-      systemctl enable $timer
-    done
-
-    lighttpd-enable-mod debmatic
-    systemctl force-reload lighttpd.service
-
-    if [ -d /usr/share/debmatic/hooks/postinst ]; then
-      run-parts /usr/share/debmatic/hooks/postinst
-    fi
-
-    systemctl start debmatic.service
+    run "Reload loader config"         ldconfig
+    run "Fix TCL symlinks"             fix_tcl_symlink
+    run "Reload udev rules"            reload_udev
+    run "Ensure command symlinks"      create_debmatic_symlinks
+    run "Create /boot/VERSION"         cp /usr/share/debmatic/VERSION /boot/VERSION
+    run "Reload systemd configuration" systemctl daemon-reload
+    run "Enable debmatic services"     enable_debmatic_services
+    run "Enable lighttpd integration"  enable_lighttpd_mod
+    run "Run postinst hooks"           run_postinst_hooks
+    run "Start debmatic"               systemctl start debmatic.service
     ;;
 
   reconfigure|abort-remove|abort-deconfigure)
diff --git a/debmatic/DEBIAN/postrm b/debmatic/DEBIAN/postrm
--- a/debmatic/DEBIAN/postrm
+++ b/debmatic/DEBIAN/postrm
@@ -1,14 +1,30 @@
 #!/bin/bash
 . /usr/share/debconf/confmodule
 
-set -e
+function throw {
+  echo $1
+  exit 1
+}
+
+function run {
+  echo -n "$1 ... "
+  shift
+  ERR=`$* 2>&1` && RC=$? || RC=$?
+  if [ $RC -eq 0 ]; then
+    echo -e "\033[0;32mDone\033[0;0m"
+  else
+    echo -e "\033[1;91mFAILED\033[0;0m"
+    echo "$ERR"
+    exit 1
+  fi
+}
 
 case "$1" in
   purge)
-    db_purge
-    rm -f /etc/default/debmatic
-    rm -rf /etc/config
-    rm -rf /etc/config_templates
+    run "Purge debconf database"       db_purge
+    run "Remove /etc/default/debmatic" rm -f /etc/default/debmatic
+    run "Remove /etc/config"           rm -rf /etc/config
+    run "Remove /etc/config_templates" rm -rf /etc/config_templates
     ;;
 
   remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
diff --git a/debmatic/DEBIAN/preinst b/debmatic/DEBIAN/preinst
--- a/debmatic/DEBIAN/preinst
+++ b/debmatic/DEBIAN/preinst
@@ -2,24 +2,46 @@
 
 . /usr/share/debconf/confmodule
 
-case "$1" in
-  install|upgrade)
-    if [ ! -z "$2" ]; then
-      OLD_CCU_VERSION=`echo "$2" | sed 's/\([0-9]\+\.[0-9]\+\.[0-9]\+\)-[0-9]\+/\1/g'`
+function throw {
+  echo $1
+  exit 1
+}
 
-      if [ "{CCU_VERSION}" != "$OLD_CCU_VERSION" ]; then
-        db_fset debmatic/has_backup seen false
-        db_input critical debmatic/has_backup || true
+function run {
+  echo -n "$1 ... "
+  shift
+  ERR=`$* 2>&1` && RC=$? || RC=$?
+  if [ $RC -eq 0 ]; then
+    echo -e "\033[0;32mDone\033[0;0m"
+  else
+    echo -e "\033[1;91mFAILED\033[0;0m"
+    echo "$ERR"
+    exit 1
+  fi
+}
+
+function warn_on_new_ccu_version {
+  if [ ! -z "$2" ]; then
+    OLD_CCU_VERSION=`echo "$2" | sed 's/\([0-9]\+\.[0-9]\+\.[0-9]\+\)-[0-9]\+/\1/g'`
+
+    if [ "{CCU_VERSION}" != "$OLD_CCU_VERSION" ]; then
+      db_fset debmatic/has_backup seen false
+      db_input critical debmatic/has_backup || true
+      db_go
+
+      db_get debmatic/has_backup
+      if [ "$RET" = "false" ]; then
+        db_input critical debmatic/err_no_backup || true
         db_go
-
-        db_get debmatic/has_backup
-        if [ "$RET" = "false" ]; then
-          db_input critical debmatic/err_no_backup || true
-          db_go
-          exit 2
-        fi
+        exit 2
       fi
     fi
+  fi
+}
+
+case "$1" in
+  install|upgrade)
+    warn_on_new_ccu_version
     ;;
 
   abort-upgrade)
diff --git a/debmatic/DEBIAN/prerm b/debmatic/DEBIAN/prerm
--- a/debmatic/DEBIAN/prerm
+++ b/debmatic/DEBIAN/prerm
@@ -1,28 +1,52 @@
 #!/bin/bash
 
-set -e
+function throw {
+  echo $1
+  exit 1
+}
+
+function run {
+  echo -n "$1 ... "
+  shift
+  ERR=`$* 2>&1` && RC=$? || RC=$?
+  if [ $RC -eq 0 ]; then
+    echo -e "\033[0;32mDone\033[0;0m"
+  else
+    echo -e "\033[1;91mFAILED\033[0;0m"
+    echo "$ERR"
+    exit 1
+  fi
+}
+
+function disable_services {
+  for timer in `ls /lib/systemd/system/debmatic*.timer | xargs -n 1 basename`
+  do
+    systemctl disable $timer || throw "Could not disable timer $timer"
+  done
+  for service in `ls /lib/systemd/system/debmatic*.service | xargs -n 1 basename`
+  do
+    if [ ! -e /lib/systemd/system/"${service%.service}.timer" ]; then
+      systemctl disable $service || throw "Could not disable service $service"
+    fi
+  done
+}
+
+function disable_lighttpd {
+  lighttpd-disable-mod debmatic || throw "Could not disable debmatic lighttpd module"
+  systemctl force-reload lighttpd.service || throw "Could not reload lighttpd configuration"
+}
+
+function cleanup_files {
+  rm -f /usr/sbin/debmatic-* || throw "Could not remove symlinks in /usr/sbin"
+  rm -f /boot/VERSION || throw "Could not remove /boot/VERSION"
+}
 
 case "$1" in
   remove|upgrade|deconfigure)
-    systemctl stop debmatic.service
-
-    for timer in `ls /lib/systemd/system/debmatic*.timer | xargs -n 1 basename`
-    do
-      systemctl disable $timer
-    done
-    for service in `ls /lib/systemd/system/debmatic*.service | xargs -n 1 basename`
-    do
-      if [ ! -e /lib/systemd/system/"${service%.service}.timer" ]; then
-        systemctl disable $service
-      fi
-    done
-
-    lighttpd-disable-mod debmatic
-    systemctl force-reload lighttpd.service
-
-    rm -f /usr/sbin/debmatic-*
-
-    rm -f /boot/VERSION
+    run "Stopping debmatic"            systemctl stop debmatic.service
+    run "Disable debmatic services"    disable_services
+    run "Disable lighttps integration" disable_lighttpd
+    run "Remove obsolete files"        cleanup_files
     ;;
 
   failed-upgrade)
